### ISSUE TITLE
repeated activation in cmk_host_registration

### ISSUE THREAD

**Issue by FloMiau** [tribe29/ansible-checkmk#10]
Hey there,

I'm a bit confused about the [cmk_host_registration role](https://github.com/tribe29/ansible-checkmk/blob/master/roles/cmk_host_registration/tasks/main.yml#L11-L22).

The checkmk_host module includes the parameter "activate_changes" which defaults to true and starts the activation after a change.

If the tasks returns with a change the handler "activate changes" which also starts the activation.

There should be a recommendation for which way to use and there should be no doubled activation.

Thanks.
Flo

**Comment by godspeed-you** [comment]
Hi @FloMiau,

sorry for the late answer. Even if I did not take a closer look into your problem, I'm aware of many problems in the current implementation of the Checkmk API. It's currently missing a well working client. The current one is just a workaround. Additionally, the current implementation will need to support both Web- and Rest-API.

Because of that, it's unlikely that I will have time to fix that, soon. :/

**Comment by coofercat** [comment]
I'll go further... the `cmk_host_registration : Add host` task (which calls `checkmk_host`) in the `cmk_host_registration` role always shows an Ansible change - even if the host in question is already in CheckMK. The handler then also runs to "apply changes", but correctly identifies that no changes are required (and doesn't report an Ansible change).

My guess is the `checkmk_host` code should ask CheckMK about the host first - if not found, or the details of the host differ from those to be applied, then make the REST call to add the host (and report an Ansible change). Otherwise don't bother with any further communications and don't return an Ansible change. That will avoid the handler wanting to run too.

I can understand if this is too tricky to do with the current implementation, but without it, it makes these roles less useful than they could otherwise be.

**Comment by robin-checkmk** [comment]
As this project was just deprecated, I will close this issue in preparation of the archival.
Head over to our [Ansible Collection](https://github.com/tribe29/ansible-collection-tribe29.checkmk) and check it out! :)
