### ISSUE TITLE
Redesign repo structure

### ISSUE THREAD

**Issue by godspeed-you** [tribe29/ansible-checkmk#18]
The current structure has been a first shoot that never was meant to be permanent. So we need to redesign the structure to be (better?) compliant to the official Ansible best practices.

Be aware: This may lead to incompatible changes to older Ansible versions. For this, we also need to set a tag for users of older Ansible versions.

**Comment by robin-checkmk** [comment]
Working notes:
- Intention: Reorganize content as collection
- Fokus on agent role for starters
- Enable initial deployment and registration of checkmk agents (complementary to agent bakery)
- Full agent management will not be  the scope of this repository, there are several community efforts already available
- Input is welcome, updates on progress as suitable
- This issue is referenced by the `legacy` tag

Current progress can be seen in the [reorganization-draft branch](https://github.com/tribe29/ansible-checkmk/tree/reorganization-draft).

**Comment by robin-checkmk** [comment]
Update: We are currently working on our very own official [Ansible Collection](https://github.com/tribe29/ansible-collection-tribe29.checkmk). So the reorganization of this repository is void ad the repository stays as it is.
